apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-was01  #k8s-test-was01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-was01 #
  template:
    metadata:
      labels:
        app: test-was01
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: test-was01 
          image: testconregyhg.azurecr.io/chicken:09629faa10c56a591fb8521990c7dead1bd6ae73
          ports:
            - containerPort: 8090 #8090

