apiVersion: v1
kind: Service
metadata:
  name: k8s-test-was01-svc
spec:
  type: ClusterIP
  selector:
    app: test-was01
  ports:
    - port: 80
      targetPort: 8090
      #targetPort: 8090
